[package]
name = "libmcaptcha"
version = "0.1.4"
authors = ["realaravinth <realaravinth@batsense.net>"]
description = "core of mCaptcha captcha system"
keywords = ["DDoS", "mcaptcha", "captcha", "pow"]
homepage = "https://mcaptcha.org"
repository = "https://github.com/realaravinth/libmcaptcha"
license = "AGPL-3.0"
edition = "2018"
readme = "README.md"

[dependencies]
actix = "0.10"

serde = "1.0.114"
serde_json = "1"

pretty_env_logger = "0.4"
log = "0.4"

derive_builder = "0.9"
derive_more = "0.99"

rand = "0.8"
pow_sha256 = { version = "0.2.1", git = "https://github.com/mcaptcha/pow_sha256" }
redis = { version = "0.20.1", features = ["tokio-comp","aio", "cluster"]  }

[dev-dependencies]
actix-rt = "1"
