[package]
name = "m_captcha"
version = "0.1.0"
authors = ["realaravinth <realaravinth@batsense.net>"]
description = "Convenient abstractions for all things credentials"
keywords = ["credentials", "password"]
homepage = "https://github.com/realaravinth/argon2-creds"
repository = "https://github.com/realaravinth/argon2-creds"
license = "AGPL-3.0"
edition = "2018"
readme = "README.md"

[workspace]
members = [ ".", "browser", "cli" ]


[dependencies]
actix = "0.10"

serde = "1.0.114"
serde_json = "1"

derive_builder = "0.9"
derive_more = "0.99"

rand = "0.8"
pow_sha256 = { version = "0.1", git = "https://github.com/mcaptcha/pow_sha256" }

[dev-dependencies]
actix-rt = "1"
