[package]
name = "libmcaptcha"
version = "0.1.4"
authors = ["realaravinth <realaravinth@batsense.net>"]
description = "core of mCaptcha captcha system"
keywords = ["DDoS", "mcaptcha", "captcha", "pow"]
homepage = "https://mcaptcha.org"
repository = "https://github.com/realaravinth/libmcaptcha"
license = "AGPL-3.0"
edition = "2018"
readme = "README.md"

[dependencies]
actix = { version =  "0.12", optional = true}

serde = "1.0.114"
serde_json = "1"

pretty_env_logger = {version = "0.4",  optional = true }
log = {version = "0.4",  optional = true }

derive_builder = "0.9"
derive_more = "0.99"

rand = {version = "0.8",  optional = true }


pow_sha256 = { version = "0.2.1", git = "https://github.com/mcaptcha/pow_sha256", optional=true }
redis = { version = "0.20.2", features = ["tokio-comp","aio", "cluster"], optional=true }
#redis = { version = "0.17.0", features = ["tokio-comp","aio", "cluster"], optional=true }

tokio = { version = "1", features = ["sync"]}

[dev-dependencies]
actix-rt = "2"

[features]
default = [
	"minimal",
	"full",
	"actix",
	"rand",
	"log",
	"pretty_env_logger",
	"pow_sha256",
	"redis"
]
minimal = []
full = []
