[package]
name = "guard"
version = "0.1.0"
authors = ["realaravinth <realaravinth@batsense.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"

sqlx = { version = "0.4.0", features = [ "runtime-actix-rustls", "postgres" ] }
argon2-creds = { version = "0.2", git = "https://github.com/realaravinth/argon2-creds" }

config = "0.10"
validator = "0.12"

derive_builder = "0.9"
derive_more = "0.99"

serde = "1"
serde_json = "1"

url = "2.2"

pretty_env_logger = "0.3"
log = "0.4"

lazy_static = "1.4"

actix-identity = "0.3"
actix-http = "2.2"
